version: '3.1'

services:
 grafana:
  image: grafana/grafana-enterprise
  restart: always
  volumes:
    - grafana-storage:/var/lib/grafana
  ports:
    - 3000:3000
  user: '472'
  environment:
    TZ: "Europe/Samara"
    command: >
      sh -c "ln -snf /usr/share/zoneinfo/$TZ /etc/localtime &&
      echo $TZ > /etc/timezone

volumes:
  grafana-storage:
        external: true
